# Netlify Build Configuration
[build]
  # Directory with the website files
  publish = "public"
  
  # Build command (none needed for this project)
  command = ""
  
  # Functions directory
  functions = "netlify/functions"

# Redirect admin page to static file
[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

# Redirect all API calls to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Custom headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
